<?php
defined( 'ABSPATH' ) or die( 'No script kiddies please!' );
function devvn_quanhuyen()
{
    return array(
        "0" => array("maqh"=>"001","name"=>"Quận Ba Đình","matp"=>"Hà Nội"),
        "1" => array("maqh"=>"002","name"=>"Quận Hoàn Kiếm","matp"=>"Hà Nội"),
        "2" => array("maqh"=>"003","name"=>"Quận Tây Hồ","matp"=>"Hà Nội"),
        "3" => array("maqh"=>"004","name"=>"Quận Long Biên","matp"=>"Hà Nội"),
        "4" => array("maqh"=>"005","name"=>"Quận Cầu Giấy","matp"=>"Hà Nội"),
        "5" => array("maqh"=>"006","name"=>"Quận Đống Đa","matp"=>"Hà Nội"),
        "6" => array("maqh"=>"007","name"=>"Quận Hai Bà Trưng","matp"=>"Hà Nội"),
        "7" => array("maqh"=>"008","name"=>"Quận Hoàng Mai","matp"=>"Hà Nội"),
        "8" => array("maqh"=>"009","name"=>"Quận Thanh Xuân","matp"=>"Hà Nội"),
        "9" => array("maqh"=>"016","name"=>"Huyện Sóc Sơn","matp"=>"Hà Nội"),
        "10" => array("maqh"=>"017","name"=>"Huyện Đông Anh","matp"=>"Hà Nội"),
        "11" => array("maqh"=>"018","name"=>"Huyện Gia Lâm","matp"=>"Hà Nội"),
        "12" => array("maqh"=>"019","name"=>"Quận Nam Từ Liêm","matp"=>"Hà Nội"),
        "13" => array("maqh"=>"020","name"=>"Huyện Thanh Trì","matp"=>"Hà Nội"),
        "14" => array("maqh"=>"021","name"=>"Quận Bắc Từ Liêm","matp"=>"Hà Nội"),
        "15" => array("maqh"=>"024","name"=>"Thành phố Hà Giang","matp"=>"Hà Giang"),
        "16" => array("maqh"=>"026","name"=>"Huyện Đồng Văn","matp"=>"Hà Giang"),
        "17" => array("maqh"=>"027","name"=>"Huyện Mèo Vạc","matp"=>"Hà Giang"),
        "18" => array("maqh"=>"028","name"=>"Huyện Yên Minh","matp"=>"Hà Giang"),
        "19" => array("maqh"=>"029","name"=>"Huyện Quản Bạ","matp"=>"Hà Giang"),
        "20" => array("maqh"=>"030","name"=>"Huyện Vị Xuyên","matp"=>"Hà Giang"),
        "21" => array("maqh"=>"031","name"=>"Huyện Bắc Mê","matp"=>"Hà Giang"),
        "22" => array("maqh"=>"032","name"=>"Huyện Hoàng Su Phì","matp"=>"Hà Giang"),
        "23" => array("maqh"=>"033","name"=>"Huyện Xín Mần","matp"=>"Hà Giang"),
        "24" => array("maqh"=>"034","name"=>"Huyện Bắc Quang","matp"=>"Hà Giang"),
        "25" => array("maqh"=>"035","name"=>"Huyện Quang Bình","matp"=>"Hà Giang"),
        "26" => array("maqh"=>"040","name"=>"Thành phố Cao Bằng","matp"=>"Cao Bằng"),
        "27" => array("maqh"=>"042","name"=>"Huyện Bảo Lâm","matp"=>"Cao Bằng"),
        "28" => array("maqh"=>"043","name"=>"Huyện Bảo Lạc","matp"=>"Cao Bằng"),
        "29" => array("maqh"=>"045","name"=>"Huyện Hà Quảng","matp"=>"Cao Bằng"),
        "30" => array("maqh"=>"047","name"=>"Huyện Trùng Khánh","matp"=>"Cao Bằng"),
        "31" => array("maqh"=>"048","name"=>"Huyện Hạ Lang","matp"=>"Cao Bằng"),
        "32" => array("maqh"=>"049","name"=>"Huyện Quảng Hòa","matp"=>"Cao Bằng"),
        "33" => array("maqh"=>"051","name"=>"Huyện Hoà An","matp"=>"Cao Bằng"),
        "34" => array("maqh"=>"052","name"=>"Huyện Nguyên Bình","matp"=>"Cao Bằng"),
        "35" => array("maqh"=>"053","name"=>"Huyện Thạch An","matp"=>"Cao Bằng"),
        "36" => array("maqh"=>"058","name"=>"Thành Phố Bắc Kạn","matp"=>"Bắc Kạn"),
        "37" => array("maqh"=>"060","name"=>"Huyện Pác Nặm","matp"=>"Bắc Kạn"),
        "38" => array("maqh"=>"061","name"=>"Huyện Ba Bể","matp"=>"Bắc Kạn"),
        "39" => array("maqh"=>"062","name"=>"Huyện Ngân Sơn","matp"=>"Bắc Kạn"),
        "40" => array("maqh"=>"063","name"=>"Huyện Bạch Thông","matp"=>"Bắc Kạn"),
        "41" => array("maqh"=>"064","name"=>"Huyện Chợ Đồn","matp"=>"Bắc Kạn"),
        "42" => array("maqh"=>"065","name"=>"Huyện Chợ Mới","matp"=>"Bắc Kạn"),
        "43" => array("maqh"=>"066","name"=>"Huyện Na Rì","matp"=>"Bắc Kạn"),
        "44" => array("maqh"=>"070","name"=>"Thành phố Tuyên Quang","matp"=>"Tuyên Quang"),
        "45" => array("maqh"=>"071","name"=>"Huyện Lâm Bình","matp"=>"Tuyên Quang"),
        "46" => array("maqh"=>"072","name"=>"Huyện Na Hang","matp"=>"Tuyên Quang"),
        "47" => array("maqh"=>"073","name"=>"Huyện Chiêm Hóa","matp"=>"Tuyên Quang"),
        "48" => array("maqh"=>"074","name"=>"Huyện Hàm Yên","matp"=>"Tuyên Quang"),
        "49" => array("maqh"=>"075","name"=>"Huyện Yên Sơn","matp"=>"Tuyên Quang"),
        "50" => array("maqh"=>"076","name"=>"Huyện Sơn Dương","matp"=>"Tuyên Quang"),
        "51" => array("maqh"=>"080","name"=>"Thành phố Lào Cai","matp"=>"Lào Cai"),
        "52" => array("maqh"=>"082","name"=>"Huyện Bát Xát","matp"=>"Lào Cai"),
        "53" => array("maqh"=>"083","name"=>"Huyện Mường Khương","matp"=>"Lào Cai"),
        "54" => array("maqh"=>"084","name"=>"Huyện Si Ma Cai","matp"=>"Lào Cai"),
        "55" => array("maqh"=>"085","name"=>"Huyện Bắc Hà","matp"=>"Lào Cai"),
        "56" => array("maqh"=>"086","name"=>"Huyện Bảo Thắng","matp"=>"Lào Cai"),
        "57" => array("maqh"=>"087","name"=>"Huyện Bảo Yên","matp"=>"Lào Cai"),
        "58" => array("maqh"=>"088","name"=>"Thị xã Sa Pa","matp"=>"Lào Cai"),
        "59" => array("maqh"=>"089","name"=>"Huyện Văn Bàn","matp"=>"Lào Cai"),
        "60" => array("maqh"=>"094","name"=>"Thành phố Điện Biên Phủ","matp"=>"Điện Biên"),
        "61" => array("maqh"=>"095","name"=>"Thị Xã Mường Lay","matp"=>"Điện Biên"),
        "62" => array("maqh"=>"096","name"=>"Huyện Mường Nhé","matp"=>"Điện Biên"),
        "63" => array("maqh"=>"097","name"=>"Huyện Mường Chà","matp"=>"Điện Biên"),
        "64" => array("maqh"=>"098","name"=>"Huyện Tủa Chùa","matp"=>"Điện Biên"),
        "65" => array("maqh"=>"099","name"=>"Huyện Tuần Giáo","matp"=>"Điện Biên"),
        "66" => array("maqh"=>"100","name"=>"Huyện Điện Biên","matp"=>"Điện Biên"),
        "67" => array("maqh"=>"101","name"=>"Huyện Điện Biên Đông","matp"=>"Điện Biên"),
        "68" => array("maqh"=>"102","name"=>"Huyện Mường Ảng","matp"=>"Điện Biên"),
        "69" => array("maqh"=>"103","name"=>"Huyện Nậm Pồ","matp"=>"Điện Biên"),
        "70" => array("maqh"=>"105","name"=>"Thành phố Lai Châu","matp"=>"Lai Châu"),
        "71" => array("maqh"=>"106","name"=>"Huyện Tam Đường","matp"=>"Lai Châu"),
        "72" => array("maqh"=>"107","name"=>"Huyện Mường Tè","matp"=>"Lai Châu"),
        "73" => array("maqh"=>"108","name"=>"Huyện Sìn Hồ","matp"=>"Lai Châu"),
        "74" => array("maqh"=>"109","name"=>"Huyện Phong Thổ","matp"=>"Lai Châu"),
        "75" => array("maqh"=>"110","name"=>"Huyện Than Uyên","matp"=>"Lai Châu"),
        "76" => array("maqh"=>"111","name"=>"Huyện Tân Uyên","matp"=>"Lai Châu"),
        "77" => array("maqh"=>"112","name"=>"Huyện Nậm Nhùn","matp"=>"Lai Châu"),
        "78" => array("maqh"=>"116","name"=>"Thành phố Sơn La","matp"=>"Sơn La"),
        "79" => array("maqh"=>"118","name"=>"Huyện Quỳnh Nhai","matp"=>"Sơn La"),
        "80" => array("maqh"=>"119","name"=>"Huyện Thuận Châu","matp"=>"Sơn La"),
        "81" => array("maqh"=>"120","name"=>"Huyện Mường La","matp"=>"Sơn La"),
        "82" => array("maqh"=>"121","name"=>"Huyện Bắc Yên","matp"=>"Sơn La"),
        "83" => array("maqh"=>"122","name"=>"Huyện Phù Yên","matp"=>"Sơn La"),
        "84" => array("maqh"=>"123","name"=>"Huyện Mộc Châu","matp"=>"Sơn La"),
        "85" => array("maqh"=>"124","name"=>"Huyện Yên Châu","matp"=>"Sơn La"),
        "86" => array("maqh"=>"125","name"=>"Huyện Mai Sơn","matp"=>"Sơn La"),
        "87" => array("maqh"=>"126","name"=>"Huyện Sông Mã","matp"=>"Sơn La"),
        "88" => array("maqh"=>"127","name"=>"Huyện Sốp Cộp","matp"=>"Sơn La"),
        "89" => array("maqh"=>"128","name"=>"Huyện Vân Hồ","matp"=>"Sơn La"),
        "90" => array("maqh"=>"132","name"=>"Thành phố Yên Bái","matp"=>"Yên Bái"),
        "91" => array("maqh"=>"133","name"=>"Thị xã Nghĩa Lộ","matp"=>"Yên Bái"),
        "92" => array("maqh"=>"135","name"=>"Huyện Lục Yên","matp"=>"Yên Bái"),
        "93" => array("maqh"=>"136","name"=>"Huyện Văn Yên","matp"=>"Yên Bái"),
        "94" => array("maqh"=>"137","name"=>"Huyện Mù Căng Chải","matp"=>"Yên Bái"),
        "95" => array("maqh"=>"138","name"=>"Huyện Trấn Yên","matp"=>"Yên Bái"),
        "96" => array("maqh"=>"139","name"=>"Huyện Trạm Tấu","matp"=>"Yên Bái"),
        "97" => array("maqh"=>"140","name"=>"Huyện Văn Chấn","matp"=>"Yên Bái"),
        "98" => array("maqh"=>"141","name"=>"Huyện Yên Bình","matp"=>"Yên Bái"),
        "99" => array("maqh"=>"148","name"=>"Thành phố Hòa Bình","matp"=>"Hoà Bình"),
        "100" => array("maqh"=>"150","name"=>"Huyện Đà Bắc","matp"=>"Hoà Bình"),
        "101" => array("maqh"=>"152","name"=>"Huyện Lương Sơn","matp"=>"Hoà Bình"),
        "102" => array("maqh"=>"153","name"=>"Huyện Kim Bôi","matp"=>"Hoà Bình"),
        "103" => array("maqh"=>"154","name"=>"Huyện Cao Phong","matp"=>"Hoà Bình"),
        "104" => array("maqh"=>"155","name"=>"Huyện Tân Lạc","matp"=>"Hoà Bình"),
        "105" => array("maqh"=>"156","name"=>"Huyện Mai Châu","matp"=>"Hoà Bình"),
        "106" => array("maqh"=>"157","name"=>"Huyện Lạc Sơn","matp"=>"Hoà Bình"),
        "107" => array("maqh"=>"158","name"=>"Huyện Yên Thủy","matp"=>"Hoà Bình"),
        "108" => array("maqh"=>"159","name"=>"Huyện Lạc Thủy","matp"=>"Hoà Bình"),
        "109" => array("maqh"=>"164","name"=>"Thành phố Thái Nguyên","matp"=>"Thái Nguyên"),
        "110" => array("maqh"=>"165","name"=>"Thành phố Sông Công","matp"=>"Thái Nguyên"),
        "111" => array("maqh"=>"167","name"=>"Huyện Định Hóa","matp"=>"Thái Nguyên"),
        "112" => array("maqh"=>"168","name"=>"Huyện Phú Lương","matp"=>"Thái Nguyên"),
        "113" => array("maqh"=>"169","name"=>"Huyện Đồng Hỷ","matp"=>"Thái Nguyên"),
        "114" => array("maqh"=>"170","name"=>"Huyện Võ Nhai","matp"=>"Thái Nguyên"),
        "115" => array("maqh"=>"171","name"=>"Huyện Đại Từ","matp"=>"Thái Nguyên"),
        "116" => array("maqh"=>"172","name"=>"Thị xã Phổ Yên","matp"=>"Thái Nguyên"),
        "117" => array("maqh"=>"173","name"=>"Huyện Phú Bình","matp"=>"Thái Nguyên"),
        "118" => array("maqh"=>"178","name"=>"Thành phố Lạng Sơn","matp"=>"Lạng Sơn"),
        "119" => array("maqh"=>"180","name"=>"Huyện Tràng Định","matp"=>"Lạng Sơn"),
        "120" => array("maqh"=>"181","name"=>"Huyện Bình Gia","matp"=>"Lạng Sơn"),
        "121" => array("maqh"=>"182","name"=>"Huyện Văn Lãng","matp"=>"Lạng Sơn"),
        "122" => array("maqh"=>"183","name"=>"Huyện Cao Lộc","matp"=>"Lạng Sơn"),
        "123" => array("maqh"=>"184","name"=>"Huyện Văn Quan","matp"=>"Lạng Sơn"),
        "124" => array("maqh"=>"185","name"=>"Huyện Bắc Sơn","matp"=>"Lạng Sơn"),
        "125" => array("maqh"=>"186","name"=>"Huyện Hữu Lũng","matp"=>"Lạng Sơn"),
        "126" => array("maqh"=>"187","name"=>"Huyện Chi Lăng","matp"=>"Lạng Sơn"),
        "127" => array("maqh"=>"188","name"=>"Huyện Lộc Bình","matp"=>"Lạng Sơn"),
        "128" => array("maqh"=>"189","name"=>"Huyện Đình Lập","matp"=>"Lạng Sơn"),
        "129" => array("maqh"=>"193","name"=>"Thành phố Hạ Long","matp"=>"Quảng Ninh"),
        "130" => array("maqh"=>"194","name"=>"Thành phố Móng Cái","matp"=>"Quảng Ninh"),
        "131" => array("maqh"=>"195","name"=>"Thành phố Cẩm Phả","matp"=>"Quảng Ninh"),
        "132" => array("maqh"=>"196","name"=>"Thành phố Uông Bí","matp"=>"Quảng Ninh"),
        "133" => array("maqh"=>"198","name"=>"Huyện Bình Liêu","matp"=>"Quảng Ninh"),
        "134" => array("maqh"=>"199","name"=>"Huyện Tiên Yên","matp"=>"Quảng Ninh"),
        "135" => array("maqh"=>"200","name"=>"Huyện Đầm Hà","matp"=>"Quảng Ninh"),
        "136" => array("maqh"=>"201","name"=>"Huyện Hải Hà","matp"=>"Quảng Ninh"),
        "137" => array("maqh"=>"202","name"=>"Huyện Ba Chẽ","matp"=>"Quảng Ninh"),
        "138" => array("maqh"=>"203","name"=>"Huyện Vân Đồn","matp"=>"Quảng Ninh"),
        "139" => array("maqh"=>"205","name"=>"Thị xã Đông Triều","matp"=>"Quảng Ninh"),
        "140" => array("maqh"=>"206","name"=>"Thị xã Quảng Yên","matp"=>"Quảng Ninh"),
        "141" => array("maqh"=>"207","name"=>"Huyện Cô Tô","matp"=>"Quảng Ninh"),
        "142" => array("maqh"=>"213","name"=>"Thành phố Bắc Giang","matp"=>"Bắc Giang"),
        "143" => array("maqh"=>"215","name"=>"Huyện Yên Thế","matp"=>"Bắc Giang"),
        "144" => array("maqh"=>"216","name"=>"Huyện Tân Yên","matp"=>"Bắc Giang"),
        "145" => array("maqh"=>"217","name"=>"Huyện Lạng Giang","matp"=>"Bắc Giang"),
        "146" => array("maqh"=>"218","name"=>"Huyện Lục Nam","matp"=>"Bắc Giang"),
        "147" => array("maqh"=>"219","name"=>"Huyện Lục Ngạn","matp"=>"Bắc Giang"),
        "148" => array("maqh"=>"220","name"=>"Huyện Sơn Động","matp"=>"Bắc Giang"),
        "149" => array("maqh"=>"221","name"=>"Huyện Yên Dũng","matp"=>"Bắc Giang"),
        "150" => array("maqh"=>"222","name"=>"Huyện Việt Yên","matp"=>"Bắc Giang"),
        "151" => array("maqh"=>"223","name"=>"Huyện Hiệp Hòa","matp"=>"Bắc Giang"),
        "152" => array("maqh"=>"227","name"=>"Thành phố Việt Trì","matp"=>"Phú Thọ"),
        "153" => array("maqh"=>"228","name"=>"Thị xã Phú Thọ","matp"=>"Phú Thọ"),
        "154" => array("maqh"=>"230","name"=>"Huyện Đoan Hùng","matp"=>"Phú Thọ"),
        "155" => array("maqh"=>"231","name"=>"Huyện Hạ Hoà","matp"=>"Phú Thọ"),
        "156" => array("maqh"=>"232","name"=>"Huyện Thanh Ba","matp"=>"Phú Thọ"),
        "157" => array("maqh"=>"233","name"=>"Huyện Phù Ninh","matp"=>"Phú Thọ"),
        "158" => array("maqh"=>"234","name"=>"Huyện Yên Lập","matp"=>"Phú Thọ"),
        "159" => array("maqh"=>"235","name"=>"Huyện Cẩm Khê","matp"=>"Phú Thọ"),
        "160" => array("maqh"=>"236","name"=>"Huyện Tam Nông","matp"=>"Phú Thọ"),
        "161" => array("maqh"=>"237","name"=>"Huyện Lâm Thao","matp"=>"Phú Thọ"),
        "162" => array("maqh"=>"238","name"=>"Huyện Thanh Sơn","matp"=>"Phú Thọ"),
        "163" => array("maqh"=>"239","name"=>"Huyện Thanh Thuỷ","matp"=>"Phú Thọ"),
        "164" => array("maqh"=>"240","name"=>"Huyện Tân Sơn","matp"=>"Phú Thọ"),
        "165" => array("maqh"=>"243","name"=>"Thành phố Vĩnh Yên","matp"=>"Vĩnh Phúc"),
        "166" => array("maqh"=>"244","name"=>"Thành phố Phúc Yên","matp"=>"Vĩnh Phúc"),
        "167" => array("maqh"=>"246","name"=>"Huyện Lập Thạch","matp"=>"Vĩnh Phúc"),
        "168" => array("maqh"=>"247","name"=>"Huyện Tam Dương","matp"=>"Vĩnh Phúc"),
        "169" => array("maqh"=>"248","name"=>"Huyện Tam Đảo","matp"=>"Vĩnh Phúc"),
        "170" => array("maqh"=>"249","name"=>"Huyện Bình Xuyên","matp"=>"Vĩnh Phúc"),
        "171" => array("maqh"=>"250","name"=>"Huyện Mê Linh","matp"=>"Hà Nội"),
        "172" => array("maqh"=>"251","name"=>"Huyện Yên Lạc","matp"=>"Vĩnh Phúc"),
        "173" => array("maqh"=>"252","name"=>"Huyện Vĩnh Tường","matp"=>"Vĩnh Phúc"),
        "174" => array("maqh"=>"253","name"=>"Huyện Sông Lô","matp"=>"Vĩnh Phúc"),
        "175" => array("maqh"=>"256","name"=>"Thành phố Bắc Ninh","matp"=>"Bắc Ninh"),
        "176" => array("maqh"=>"258","name"=>"Huyện Yên Phong","matp"=>"Bắc Ninh"),
        "177" => array("maqh"=>"259","name"=>"Huyện Quế Võ","matp"=>"Bắc Ninh"),
        "178" => array("maqh"=>"260","name"=>"Huyện Tiên Du","matp"=>"Bắc Ninh"),
        "179" => array("maqh"=>"261","name"=>"Thị xã Từ Sơn","matp"=>"Bắc Ninh"),
        "180" => array("maqh"=>"262","name"=>"Huyện Thuận Thành","matp"=>"Bắc Ninh"),
        "181" => array("maqh"=>"263","name"=>"Huyện Gia Bình","matp"=>"Bắc Ninh"),
        "182" => array("maqh"=>"264","name"=>"Huyện Lương Tài","matp"=>"Bắc Ninh"),
        "183" => array("maqh"=>"268","name"=>"Quận Hà Đông","matp"=>"Hà Nội"),
        "184" => array("maqh"=>"269","name"=>"Thị xã Sơn Tây","matp"=>"Hà Nội"),
        "185" => array("maqh"=>"271","name"=>"Huyện Ba Vì","matp"=>"Hà Nội"),
        "186" => array("maqh"=>"272","name"=>"Huyện Phúc Thọ","matp"=>"Hà Nội"),
        "187" => array("maqh"=>"273","name"=>"Huyện Đan Phượng","matp"=>"Hà Nội"),
        "188" => array("maqh"=>"274","name"=>"Huyện Hoài Đức","matp"=>"Hà Nội"),
        "189" => array("maqh"=>"275","name"=>"Huyện Quốc Oai","matp"=>"Hà Nội"),
        "190" => array("maqh"=>"276","name"=>"Huyện Thạch Thất","matp"=>"Hà Nội"),
        "191" => array("maqh"=>"277","name"=>"Huyện Chương Mỹ","matp"=>"Hà Nội"),
        "192" => array("maqh"=>"278","name"=>"Huyện Thanh Oai","matp"=>"Hà Nội"),
        "193" => array("maqh"=>"279","name"=>"Huyện Thường Tín","matp"=>"Hà Nội"),
        "194" => array("maqh"=>"280","name"=>"Huyện Phú Xuyên","matp"=>"Hà Nội"),
        "195" => array("maqh"=>"281","name"=>"Huyện Ứng Hòa","matp"=>"Hà Nội"),
        "196" => array("maqh"=>"282","name"=>"Huyện Mỹ Đức","matp"=>"Hà Nội"),
        "197" => array("maqh"=>"288","name"=>"Thành phố Hải Dương","matp"=>"Hải Dương"),
        "198" => array("maqh"=>"290","name"=>"Thành phố Chí Linh","matp"=>"Hải Dương"),
        "199" => array("maqh"=>"291","name"=>"Huyện Nam Sách","matp"=>"Hải Dương"),
        "200" => array("maqh"=>"292","name"=>"Thị xã Kinh Môn","matp"=>"Hải Dương"),
        "201" => array("maqh"=>"293","name"=>"Huyện Kim Thành","matp"=>"Hải Dương"),
        "202" => array("maqh"=>"294","name"=>"Huyện Thanh Hà","matp"=>"Hải Dương"),
        "203" => array("maqh"=>"295","name"=>"Huyện Cẩm Giàng","matp"=>"Hải Dương"),
        "204" => array("maqh"=>"296","name"=>"Huyện Bình Giang","matp"=>"Hải Dương"),
        "205" => array("maqh"=>"297","name"=>"Huyện Gia Lộc","matp"=>"Hải Dương"),
        "206" => array("maqh"=>"298","name"=>"Huyện Tứ Kỳ","matp"=>"Hải Dương"),
        "207" => array("maqh"=>"299","name"=>"Huyện Ninh Giang","matp"=>"Hải Dương"),
        "208" => array("maqh"=>"300","name"=>"Huyện Thanh Miện","matp"=>"Hải Dương"),
        "209" => array("maqh"=>"303","name"=>"Quận Hồng Bàng","matp"=>"Hải Phòng"),
        "210" => array("maqh"=>"304","name"=>"Quận Ngô Quyền","matp"=>"Hải Phòng"),
        "211" => array("maqh"=>"305","name"=>"Quận Lê Chân","matp"=>"Hải Phòng"),
        "212" => array("maqh"=>"306","name"=>"Quận Hải An","matp"=>"Hải Phòng"),
        "213" => array("maqh"=>"307","name"=>"Quận Kiến An","matp"=>"Hải Phòng"),
        "214" => array("maqh"=>"308","name"=>"Quận Đồ Sơn","matp"=>"Hải Phòng"),
        "215" => array("maqh"=>"309","name"=>"Quận Dương Kinh","matp"=>"Hải Phòng"),
        "216" => array("maqh"=>"311","name"=>"Huyện Thuỷ Nguyên","matp"=>"Hải Phòng"),
        "217" => array("maqh"=>"312","name"=>"Huyện An Dương","matp"=>"Hải Phòng"),
        "218" => array("maqh"=>"313","name"=>"Huyện An Lão","matp"=>"Hải Phòng"),
        "219" => array("maqh"=>"314","name"=>"Huyện Kiến Thuỵ","matp"=>"Hải Phòng"),
        "220" => array("maqh"=>"315","name"=>"Huyện Tiên Lãng","matp"=>"Hải Phòng"),
        "221" => array("maqh"=>"316","name"=>"Huyện Vĩnh Bảo","matp"=>"Hải Phòng"),
        "222" => array("maqh"=>"317","name"=>"Huyện Cát Hải","matp"=>"Hải Phòng"),
        "223" => array("maqh"=>"318","name"=>"Huyện Bạch Long Vĩ","matp"=>"Hải Phòng"),
        "224" => array("maqh"=>"323","name"=>"Thành phố Hưng Yên","matp"=>"Hưng Yên"),
        "225" => array("maqh"=>"325","name"=>"Huyện Văn Lâm","matp"=>"Hưng Yên"),
        "226" => array("maqh"=>"326","name"=>"Huyện Văn Giang","matp"=>"Hưng Yên"),
        "227" => array("maqh"=>"327","name"=>"Huyện Yên Mỹ","matp"=>"Hưng Yên"),
        "228" => array("maqh"=>"328","name"=>"Thị xã Mỹ Hào","matp"=>"Hưng Yên"),
        "229" => array("maqh"=>"329","name"=>"Huyện Ân Thi","matp"=>"Hưng Yên"),
        "230" => array("maqh"=>"330","name"=>"Huyện Khoái Châu","matp"=>"Hưng Yên"),
        "231" => array("maqh"=>"331","name"=>"Huyện Kim Động","matp"=>"Hưng Yên"),
        "232" => array("maqh"=>"332","name"=>"Huyện Tiên Lữ","matp"=>"Hưng Yên"),
        "233" => array("maqh"=>"333","name"=>"Huyện Phù Cừ","matp"=>"Hưng Yên"),
        "234" => array("maqh"=>"336","name"=>"Thành phố Thái Bình","matp"=>"Thái Bình"),
        "235" => array("maqh"=>"338","name"=>"Huyện Quỳnh Phụ","matp"=>"Thái Bình"),
        "236" => array("maqh"=>"339","name"=>"Huyện Hưng Hà","matp"=>"Thái Bình"),
        "237" => array("maqh"=>"340","name"=>"Huyện Đông Hưng","matp"=>"Thái Bình"),
        "238" => array("maqh"=>"341","name"=>"Huyện Thái Thụy","matp"=>"Thái Bình"),
        "239" => array("maqh"=>"342","name"=>"Huyện Tiền Hải","matp"=>"Thái Bình"),
        "240" => array("maqh"=>"343","name"=>"Huyện Kiến Xương","matp"=>"Thái Bình"),
        "241" => array("maqh"=>"344","name"=>"Huyện Vũ Thư","matp"=>"Thái Bình"),
        "242" => array("maqh"=>"347","name"=>"Thành phố Phủ Lý","matp"=>"Hà Nam"),
        "243" => array("maqh"=>"349","name"=>"Thị xã Duy Tiên","matp"=>"Hà Nam"),
        "244" => array("maqh"=>"350","name"=>"Huyện Kim Bảng","matp"=>"Hà Nam"),
        "245" => array("maqh"=>"351","name"=>"Huyện Thanh Liêm","matp"=>"Hà Nam"),
        "246" => array("maqh"=>"352","name"=>"Huyện Bình Lục","matp"=>"Hà Nam"),
        "247" => array("maqh"=>"353","name"=>"Huyện Lý Nhân","matp"=>"Hà Nam"),
        "248" => array("maqh"=>"356","name"=>"Thành phố Nam Định","matp"=>"Nam Định"),
        "249" => array("maqh"=>"358","name"=>"Huyện Mỹ Lộc","matp"=>"Nam Định"),
        "250" => array("maqh"=>"359","name"=>"Huyện Vụ Bản","matp"=>"Nam Định"),
        "251" => array("maqh"=>"360","name"=>"Huyện Ý Yên","matp"=>"Nam Định"),
        "252" => array("maqh"=>"361","name"=>"Huyện Nghĩa Hưng","matp"=>"Nam Định"),
        "253" => array("maqh"=>"362","name"=>"Huyện Nam Trực","matp"=>"Nam Định"),
        "254" => array("maqh"=>"363","name"=>"Huyện Trực Ninh","matp"=>"Nam Định"),
        "255" => array("maqh"=>"364","name"=>"Huyện Xuân Trường","matp"=>"Nam Định"),
        "256" => array("maqh"=>"365","name"=>"Huyện Giao Thủy","matp"=>"Nam Định"),
        "257" => array("maqh"=>"366","name"=>"Huyện Hải Hậu","matp"=>"Nam Định"),
        "258" => array("maqh"=>"369","name"=>"Thành phố Ninh Bình","matp"=>"Ninh Bình"),
        "259" => array("maqh"=>"370","name"=>"Thành phố Tam Điệp","matp"=>"Ninh Bình"),
        "260" => array("maqh"=>"372","name"=>"Huyện Nho Quan","matp"=>"Ninh Bình"),
        "261" => array("maqh"=>"373","name"=>"Huyện Gia Viễn","matp"=>"Ninh Bình"),
        "262" => array("maqh"=>"374","name"=>"Huyện Hoa Lư","matp"=>"Ninh Bình"),
        "263" => array("maqh"=>"375","name"=>"Huyện Yên Khánh","matp"=>"Ninh Bình"),
        "264" => array("maqh"=>"376","name"=>"Huyện Kim Sơn","matp"=>"Ninh Bình"),
        "265" => array("maqh"=>"377","name"=>"Huyện Yên Mô","matp"=>"Ninh Bình"),
        "266" => array("maqh"=>"380","name"=>"Thành phố Thanh Hóa","matp"=>"Thanh Hóa"),
        "267" => array("maqh"=>"381","name"=>"Thị xã Bỉm Sơn","matp"=>"Thanh Hóa"),
        "268" => array("maqh"=>"382","name"=>"Thành phố Sầm Sơn","matp"=>"Thanh Hóa"),
        "269" => array("maqh"=>"384","name"=>"Huyện Mường Lát","matp"=>"Thanh Hóa"),
        "270" => array("maqh"=>"385","name"=>"Huyện Quan Hóa","matp"=>"Thanh Hóa"),
        "271" => array("maqh"=>"386","name"=>"Huyện Bá Thước","matp"=>"Thanh Hóa"),
        "272" => array("maqh"=>"387","name"=>"Huyện Quan Sơn","matp"=>"Thanh Hóa"),
        "273" => array("maqh"=>"388","name"=>"Huyện Lang Chánh","matp"=>"Thanh Hóa"),
        "274" => array("maqh"=>"389","name"=>"Huyện Ngọc Lặc","matp"=>"Thanh Hóa"),
        "275" => array("maqh"=>"390","name"=>"Huyện Cẩm Thủy","matp"=>"Thanh Hóa"),
        "276" => array("maqh"=>"391","name"=>"Huyện Thạch Thành","matp"=>"Thanh Hóa"),
        "277" => array("maqh"=>"392","name"=>"Huyện Hà Trung","matp"=>"Thanh Hóa"),
        "278" => array("maqh"=>"393","name"=>"Huyện Vĩnh Lộc","matp"=>"Thanh Hóa"),
        "279" => array("maqh"=>"394","name"=>"Huyện Yên Định","matp"=>"Thanh Hóa"),
        "280" => array("maqh"=>"395","name"=>"Huyện Thọ Xuân","matp"=>"Thanh Hóa"),
        "281" => array("maqh"=>"396","name"=>"Huyện Thường Xuân","matp"=>"Thanh Hóa"),
        "282" => array("maqh"=>"397","name"=>"Huyện Triệu Sơn","matp"=>"Thanh Hóa"),
        "283" => array("maqh"=>"398","name"=>"Huyện Thiệu Hóa","matp"=>"Thanh Hóa"),
        "284" => array("maqh"=>"399","name"=>"Huyện Hoằng Hóa","matp"=>"Thanh Hóa"),
        "285" => array("maqh"=>"400","name"=>"Huyện Hậu Lộc","matp"=>"Thanh Hóa"),
        "286" => array("maqh"=>"401","name"=>"Huyện Nga Sơn","matp"=>"Thanh Hóa"),
        "287" => array("maqh"=>"402","name"=>"Huyện Như Xuân","matp"=>"Thanh Hóa"),
        "288" => array("maqh"=>"403","name"=>"Huyện Như Thanh","matp"=>"Thanh Hóa"),
        "289" => array("maqh"=>"404","name"=>"Huyện Nông Cống","matp"=>"Thanh Hóa"),
        "290" => array("maqh"=>"405","name"=>"Huyện Đông Sơn","matp"=>"Thanh Hóa"),
        "291" => array("maqh"=>"406","name"=>"Huyện Quảng Xương","matp"=>"Thanh Hóa"),
        "292" => array("maqh"=>"407","name"=>"Thị xã Nghi Sơn","matp"=>"Thanh Hóa"),
        "293" => array("maqh"=>"412","name"=>"Thành phố Vinh","matp"=>"Nghệ An"),
        "294" => array("maqh"=>"413","name"=>"Thị xã Cửa Lò","matp"=>"Nghệ An"),
        "295" => array("maqh"=>"414","name"=>"Thị xã Thái Hoà","matp"=>"Nghệ An"),
        "296" => array("maqh"=>"415","name"=>"Huyện Quế Phong","matp"=>"Nghệ An"),
        "297" => array("maqh"=>"416","name"=>"Huyện Quỳ Châu","matp"=>"Nghệ An"),
        "298" => array("maqh"=>"417","name"=>"Huyện Kỳ Sơn","matp"=>"Nghệ An"),
        "299" => array("maqh"=>"418","name"=>"Huyện Tương Dương","matp"=>"Nghệ An"),
        "300" => array("maqh"=>"419","name"=>"Huyện Nghĩa Đàn","matp"=>"Nghệ An"),
        "301" => array("maqh"=>"420","name"=>"Huyện Quỳ Hợp","matp"=>"Nghệ An"),
        "302" => array("maqh"=>"421","name"=>"Huyện Quỳnh Lưu","matp"=>"Nghệ An"),
        "303" => array("maqh"=>"422","name"=>"Huyện Con Cuông","matp"=>"Nghệ An"),
        "304" => array("maqh"=>"423","name"=>"Huyện Tân Kỳ","matp"=>"Nghệ An"),
        "305" => array("maqh"=>"424","name"=>"Huyện Anh Sơn","matp"=>"Nghệ An"),
        "306" => array("maqh"=>"425","name"=>"Huyện Diễn Châu","matp"=>"Nghệ An"),
        "307" => array("maqh"=>"426","name"=>"Huyện Yên Thành","matp"=>"Nghệ An"),
        "308" => array("maqh"=>"427","name"=>"Huyện Đô Lương","matp"=>"Nghệ An"),
        "309" => array("maqh"=>"428","name"=>"Huyện Thanh Chương","matp"=>"Nghệ An"),
        "310" => array("maqh"=>"429","name"=>"Huyện Nghi Lộc","matp"=>"Nghệ An"),
        "311" => array("maqh"=>"430","name"=>"Huyện Nam Đàn","matp"=>"Nghệ An"),
        "312" => array("maqh"=>"431","name"=>"Huyện Hưng Nguyên","matp"=>"Nghệ An"),
        "313" => array("maqh"=>"432","name"=>"Thị xã Hoàng Mai","matp"=>"Nghệ An"),
        "314" => array("maqh"=>"436","name"=>"Thành phố Hà Tĩnh","matp"=>"Hà Tĩnh"),
        "315" => array("maqh"=>"437","name"=>"Thị xã Hồng Lĩnh","matp"=>"Hà Tĩnh"),
        "316" => array("maqh"=>"439","name"=>"Huyện Hương Sơn","matp"=>"Hà Tĩnh"),
        "317" => array("maqh"=>"440","name"=>"Huyện Đức Thọ","matp"=>"Hà Tĩnh"),
        "318" => array("maqh"=>"441","name"=>"Huyện Vũ Quang","matp"=>"Hà Tĩnh"),
        "319" => array("maqh"=>"442","name"=>"Huyện Nghi Xuân","matp"=>"Hà Tĩnh"),
        "320" => array("maqh"=>"443","name"=>"Huyện Can Lộc","matp"=>"Hà Tĩnh"),
        "321" => array("maqh"=>"444","name"=>"Huyện Hương Khê","matp"=>"Hà Tĩnh"),
        "322" => array("maqh"=>"445","name"=>"Huyện Thạch Hà","matp"=>"Hà Tĩnh"),
        "323" => array("maqh"=>"446","name"=>"Huyện Cẩm Xuyên","matp"=>"Hà Tĩnh"),
        "324" => array("maqh"=>"447","name"=>"Huyện Kỳ Anh","matp"=>"Hà Tĩnh"),
        "325" => array("maqh"=>"448","name"=>"Huyện Lộc Hà","matp"=>"Hà Tĩnh"),
        "326" => array("maqh"=>"449","name"=>"Thị xã Kỳ Anh","matp"=>"Hà Tĩnh"),
        "327" => array("maqh"=>"450","name"=>"Thành Phố Đồng Hới","matp"=>"Quảng Bình"),
        "328" => array("maqh"=>"452","name"=>"Huyện Minh Hóa","matp"=>"Quảng Bình"),
        "329" => array("maqh"=>"453","name"=>"Huyện Tuyên Hóa","matp"=>"Quảng Bình"),
        "330" => array("maqh"=>"454","name"=>"Huyện Quảng Trạch","matp"=>"Quảng Bình"),
        "331" => array("maqh"=>"455","name"=>"Huyện Bố Trạch","matp"=>"Quảng Bình"),
        "332" => array("maqh"=>"456","name"=>"Huyện Quảng Ninh","matp"=>"Quảng Bình"),
        "333" => array("maqh"=>"457","name"=>"Huyện Lệ Thủy","matp"=>"Quảng Bình"),
        "334" => array("maqh"=>"458","name"=>"Thị xã Ba Đồn","matp"=>"Quảng Bình"),
        "335" => array("maqh"=>"461","name"=>"Thành phố Đông Hà","matp"=>"Quảng Trị"),
        "336" => array("maqh"=>"462","name"=>"Thị xã Quảng Trị","matp"=>"Quảng Trị"),
        "337" => array("maqh"=>"464","name"=>"Huyện Vĩnh Linh","matp"=>"Quảng Trị"),
        "338" => array("maqh"=>"465","name"=>"Huyện Hướng Hóa","matp"=>"Quảng Trị"),
        "339" => array("maqh"=>"466","name"=>"Huyện Gio Linh","matp"=>"Quảng Trị"),
        "340" => array("maqh"=>"467","name"=>"Huyện Đa Krông","matp"=>"Quảng Trị"),
        "341" => array("maqh"=>"468","name"=>"Huyện Cam Lộ","matp"=>"Quảng Trị"),
        "342" => array("maqh"=>"469","name"=>"Huyện Triệu Phong","matp"=>"Quảng Trị"),
        "343" => array("maqh"=>"470","name"=>"Huyện Hải Lăng","matp"=>"Quảng Trị"),
        "344" => array("maqh"=>"471","name"=>"Huyện Cồn Cỏ","matp"=>"Quảng Trị"),
        "345" => array("maqh"=>"474","name"=>"Thành phố Huế","matp"=>"Thừa Thiên Huế"),
        "346" => array("maqh"=>"476","name"=>"Huyện Phong Điền","matp"=>"Thừa Thiên Huế"),
        "347" => array("maqh"=>"477","name"=>"Huyện Quảng Điền","matp"=>"Thừa Thiên Huế"),
        "348" => array("maqh"=>"478","name"=>"Huyện Phú Vang","matp"=>"Thừa Thiên Huế"),
        "349" => array("maqh"=>"479","name"=>"Thị xã Hương Thủy","matp"=>"Thừa Thiên Huế"),
        "350" => array("maqh"=>"480","name"=>"Thị xã Hương Trà","matp"=>"Thừa Thiên Huế"),
        "351" => array("maqh"=>"481","name"=>"Huyện A Lưới","matp"=>"Thừa Thiên Huế"),
        "352" => array("maqh"=>"482","name"=>"Huyện Phú Lộc","matp"=>"Thừa Thiên Huế"),
        "353" => array("maqh"=>"483","name"=>"Huyện Nam Đông","matp"=>"Thừa Thiên Huế"),
        "354" => array("maqh"=>"490","name"=>"Quận Liên Chiểu","matp"=>"Đà Nẵng"),
        "355" => array("maqh"=>"491","name"=>"Quận Thanh Khê","matp"=>"Đà Nẵng"),
        "356" => array("maqh"=>"492","name"=>"Quận Hải Châu","matp"=>"Đà Nẵng"),
        "357" => array("maqh"=>"493","name"=>"Quận Sơn Trà","matp"=>"Đà Nẵng"),
        "358" => array("maqh"=>"494","name"=>"Quận Ngũ Hành Sơn","matp"=>"Đà Nẵng"),
        "359" => array("maqh"=>"495","name"=>"Quận Cẩm Lệ","matp"=>"Đà Nẵng"),
        "360" => array("maqh"=>"497","name"=>"Huyện Hòa Vang","matp"=>"Đà Nẵng"),
        "361" => array("maqh"=>"498","name"=>"Huyện Hoàng Sa","matp"=>"Đà Nẵng"),
        "362" => array("maqh"=>"502","name"=>"Thành phố Tam Kỳ","matp"=>"Quảng Nam"),
        "363" => array("maqh"=>"503","name"=>"Thành phố Hội An","matp"=>"Quảng Nam"),
        "364" => array("maqh"=>"504","name"=>"Huyện Tây Giang","matp"=>"Quảng Nam"),
        "365" => array("maqh"=>"505","name"=>"Huyện Đông Giang","matp"=>"Quảng Nam"),
        "366" => array("maqh"=>"506","name"=>"Huyện Đại Lộc","matp"=>"Quảng Nam"),
        "367" => array("maqh"=>"507","name"=>"Thị xã Điện Bàn","matp"=>"Quảng Nam"),
        "368" => array("maqh"=>"508","name"=>"Huyện Duy Xuyên","matp"=>"Quảng Nam"),
        "369" => array("maqh"=>"509","name"=>"Huyện Quế Sơn","matp"=>"Quảng Nam"),
        "370" => array("maqh"=>"510","name"=>"Huyện Nam Giang","matp"=>"Quảng Nam"),
        "371" => array("maqh"=>"511","name"=>"Huyện Phước Sơn","matp"=>"Quảng Nam"),
        "372" => array("maqh"=>"512","name"=>"Huyện Hiệp Đức","matp"=>"Quảng Nam"),
        "373" => array("maqh"=>"513","name"=>"Huyện Thăng Bình","matp"=>"Quảng Nam"),
        "374" => array("maqh"=>"514","name"=>"Huyện Tiên Phước","matp"=>"Quảng Nam"),
        "375" => array("maqh"=>"515","name"=>"Huyện Bắc Trà My","matp"=>"Quảng Nam"),
        "376" => array("maqh"=>"516","name"=>"Huyện Nam Trà My","matp"=>"Quảng Nam"),
        "377" => array("maqh"=>"517","name"=>"Huyện Núi Thành","matp"=>"Quảng Nam"),
        "378" => array("maqh"=>"518","name"=>"Huyện Phú Ninh","matp"=>"Quảng Nam"),
        "379" => array("maqh"=>"519","name"=>"Huyện Nông Sơn","matp"=>"Quảng Nam"),
        "380" => array("maqh"=>"522","name"=>"Thành phố Quảng Ngãi","matp"=>"Quảng Ngãi"),
        "381" => array("maqh"=>"524","name"=>"Huyện Bình Sơn","matp"=>"Quảng Ngãi"),
        "382" => array("maqh"=>"525","name"=>"Huyện Trà Bồng","matp"=>"Quảng Ngãi"),
        "383" => array("maqh"=>"527","name"=>"Huyện Sơn Tịnh","matp"=>"Quảng Ngãi"),
        "384" => array("maqh"=>"528","name"=>"Huyện Tư Nghĩa","matp"=>"Quảng Ngãi"),
        "385" => array("maqh"=>"529","name"=>"Huyện Sơn Hà","matp"=>"Quảng Ngãi"),
        "386" => array("maqh"=>"530","name"=>"Huyện Sơn Tây","matp"=>"Quảng Ngãi"),
        "387" => array("maqh"=>"531","name"=>"Huyện Minh Long","matp"=>"Quảng Ngãi"),
        "388" => array("maqh"=>"532","name"=>"Huyện Nghĩa Hành","matp"=>"Quảng Ngãi"),
        "389" => array("maqh"=>"533","name"=>"Huyện Mộ Đức","matp"=>"Quảng Ngãi"),
        "390" => array("maqh"=>"534","name"=>"Thị xã Đức Phổ","matp"=>"Quảng Ngãi"),
        "391" => array("maqh"=>"535","name"=>"Huyện Ba Tơ","matp"=>"Quảng Ngãi"),
        "392" => array("maqh"=>"536","name"=>"Huyện Lý Sơn","matp"=>"Quảng Ngãi"),
        "393" => array("maqh"=>"540","name"=>"Thành phố Quy Nhơn","matp"=>"Bình Định"),
        "394" => array("maqh"=>"542","name"=>"Huyện An Lão","matp"=>"Bình Định"),
        "395" => array("maqh"=>"543","name"=>"Thị xã Hoài Nhơn","matp"=>"Bình Định"),
        "396" => array("maqh"=>"544","name"=>"Huyện Hoài Ân","matp"=>"Bình Định"),
        "397" => array("maqh"=>"545","name"=>"Huyện Phù Mỹ","matp"=>"Bình Định"),
        "398" => array("maqh"=>"546","name"=>"Huyện Vĩnh Thạnh","matp"=>"Bình Định"),
        "399" => array("maqh"=>"547","name"=>"Huyện Tây Sơn","matp"=>"Bình Định"),
        "400" => array("maqh"=>"548","name"=>"Huyện Phù Cát","matp"=>"Bình Định"),
        "401" => array("maqh"=>"549","name"=>"Thị xã An Nhơn","matp"=>"Bình Định"),
        "402" => array("maqh"=>"550","name"=>"Huyện Tuy Phước","matp"=>"Bình Định"),
        "403" => array("maqh"=>"551","name"=>"Huyện Vân Canh","matp"=>"Bình Định"),
        "404" => array("maqh"=>"555","name"=>"Thành phố Tuy Hoà","matp"=>"Phú Yên"),
        "405" => array("maqh"=>"557","name"=>"Thị xã Sông Cầu","matp"=>"Phú Yên"),
        "406" => array("maqh"=>"558","name"=>"Huyện Đồng Xuân","matp"=>"Phú Yên"),
        "407" => array("maqh"=>"559","name"=>"Huyện Tuy An","matp"=>"Phú Yên"),
        "408" => array("maqh"=>"560","name"=>"Huyện Sơn Hòa","matp"=>"Phú Yên"),
        "409" => array("maqh"=>"561","name"=>"Huyện Sông Hinh","matp"=>"Phú Yên"),
        "410" => array("maqh"=>"562","name"=>"Huyện Tây Hoà","matp"=>"Phú Yên"),
        "411" => array("maqh"=>"563","name"=>"Huyện Phú Hoà","matp"=>"Phú Yên"),
        "412" => array("maqh"=>"564","name"=>"Thị xã Đông Hòa","matp"=>"Phú Yên"),
        "413" => array("maqh"=>"568","name"=>"Thành phố Nha Trang","matp"=>"Khánh Hòa"),
        "414" => array("maqh"=>"569","name"=>"Thành phố Cam Ranh","matp"=>"Khánh Hòa"),
        "415" => array("maqh"=>"570","name"=>"Huyện Cam Lâm","matp"=>"Khánh Hòa"),
        "416" => array("maqh"=>"571","name"=>"Huyện Vạn Ninh","matp"=>"Khánh Hòa"),
        "417" => array("maqh"=>"572","name"=>"Thị xã Ninh Hòa","matp"=>"Khánh Hòa"),
        "418" => array("maqh"=>"573","name"=>"Huyện Khánh Vĩnh","matp"=>"Khánh Hòa"),
        "419" => array("maqh"=>"574","name"=>"Huyện Diên Khánh","matp"=>"Khánh Hòa"),
        "420" => array("maqh"=>"575","name"=>"Huyện Khánh Sơn","matp"=>"Khánh Hòa"),
        "421" => array("maqh"=>"576","name"=>"Huyện Trường Sa","matp"=>"Khánh Hòa"),
        "422" => array("maqh"=>"582","name"=>"Thành phố Phan Rang-Tháp Chàm","matp"=>"Ninh Thuận"),
        "423" => array("maqh"=>"584","name"=>"Huyện Bác Ái","matp"=>"Ninh Thuận"),
        "424" => array("maqh"=>"585","name"=>"Huyện Ninh Sơn","matp"=>"Ninh Thuận"),
        "425" => array("maqh"=>"586","name"=>"Huyện Ninh Hải","matp"=>"Ninh Thuận"),
        "426" => array("maqh"=>"587","name"=>"Huyện Ninh Phước","matp"=>"Ninh Thuận"),
        "427" => array("maqh"=>"588","name"=>"Huyện Thuận Bắc","matp"=>"Ninh Thuận"),
        "428" => array("maqh"=>"589","name"=>"Huyện Thuận Nam","matp"=>"Ninh Thuận"),
        "429" => array("maqh"=>"593","name"=>"Thành phố Phan Thiết","matp"=>"Bình Thuận"),
        "430" => array("maqh"=>"594","name"=>"Thị xã La Gi","matp"=>"Bình Thuận"),
        "431" => array("maqh"=>"595","name"=>"Huyện Tuy Phong","matp"=>"Bình Thuận"),
        "432" => array("maqh"=>"596","name"=>"Huyện Bắc Bình","matp"=>"Bình Thuận"),
        "433" => array("maqh"=>"597","name"=>"Huyện Hàm Thuận Bắc","matp"=>"Bình Thuận"),
        "434" => array("maqh"=>"598","name"=>"Huyện Hàm Thuận Nam","matp"=>"Bình Thuận"),
        "435" => array("maqh"=>"599","name"=>"Huyện Tánh Linh","matp"=>"Bình Thuận"),
        "436" => array("maqh"=>"600","name"=>"Huyện Đức Linh","matp"=>"Bình Thuận"),
        "437" => array("maqh"=>"601","name"=>"Huyện Hàm Tân","matp"=>"Bình Thuận"),
        "438" => array("maqh"=>"602","name"=>"Huyện Phú Quí","matp"=>"Bình Thuận"),
        "439" => array("maqh"=>"608","name"=>"Thành phố Kon Tum","matp"=>"Kon Tum"),
        "440" => array("maqh"=>"610","name"=>"Huyện Đắk Glei","matp"=>"Kon Tum"),
        "441" => array("maqh"=>"611","name"=>"Huyện Ngọc Hồi","matp"=>"Kon Tum"),
        "442" => array("maqh"=>"612","name"=>"Huyện Đắk Tô","matp"=>"Kon Tum"),
        "443" => array("maqh"=>"613","name"=>"Huyện Kon Plông","matp"=>"Kon Tum"),
        "444" => array("maqh"=>"614","name"=>"Huyện Kon Rẫy","matp"=>"Kon Tum"),
        "445" => array("maqh"=>"615","name"=>"Huyện Đắk Hà","matp"=>"Kon Tum"),
        "446" => array("maqh"=>"616","name"=>"Huyện Sa Thầy","matp"=>"Kon Tum"),
        "447" => array("maqh"=>"617","name"=>"Huyện Tu Mơ Rông","matp"=>"Kon Tum"),
        "448" => array("maqh"=>"618","name"=>"Huyện Ia H' Drai","matp"=>"Kon Tum"),
        "449" => array("maqh"=>"622","name"=>"Thành phố Pleiku","matp"=>"Gia Lai"),
        "450" => array("maqh"=>"623","name"=>"Thị xã An Khê","matp"=>"Gia Lai"),
        "451" => array("maqh"=>"624","name"=>"Thị xã Ayun Pa","matp"=>"Gia Lai"),
        "452" => array("maqh"=>"625","name"=>"Huyện KBang","matp"=>"Gia Lai"),
        "453" => array("maqh"=>"626","name"=>"Huyện Đăk Đoa","matp"=>"Gia Lai"),
        "454" => array("maqh"=>"627","name"=>"Huyện Chư Păh","matp"=>"Gia Lai"),
        "455" => array("maqh"=>"628","name"=>"Huyện Ia Grai","matp"=>"Gia Lai"),
        "456" => array("maqh"=>"629","name"=>"Huyện Mang Yang","matp"=>"Gia Lai"),
        "457" => array("maqh"=>"630","name"=>"Huyện Kông Chro","matp"=>"Gia Lai"),
        "458" => array("maqh"=>"631","name"=>"Huyện Đức Cơ","matp"=>"Gia Lai"),
        "459" => array("maqh"=>"632","name"=>"Huyện Chư Prông","matp"=>"Gia Lai"),
        "460" => array("maqh"=>"633","name"=>"Huyện Chư Sê","matp"=>"Gia Lai"),
        "461" => array("maqh"=>"634","name"=>"Huyện Đăk Pơ","matp"=>"Gia Lai"),
        "462" => array("maqh"=>"635","name"=>"Huyện Ia Pa","matp"=>"Gia Lai"),
        "463" => array("maqh"=>"637","name"=>"Huyện Krông Pa","matp"=>"Gia Lai"),
        "464" => array("maqh"=>"638","name"=>"Huyện Phú Thiện","matp"=>"Gia Lai"),
        "465" => array("maqh"=>"639","name"=>"Huyện Chư Pưh","matp"=>"Gia Lai"),
        "466" => array("maqh"=>"643","name"=>"Thành phố Buôn Ma Thuột","matp"=>"Đắk Lắk"),
        "467" => array("maqh"=>"644","name"=>"Thị Xã Buôn Hồ","matp"=>"Đắk Lắk"),
        "468" => array("maqh"=>"645","name"=>"Huyện Ea H'leo","matp"=>"Đắk Lắk"),
        "469" => array("maqh"=>"646","name"=>"Huyện Ea Súp","matp"=>"Đắk Lắk"),
        "470" => array("maqh"=>"647","name"=>"Huyện Buôn Đôn","matp"=>"Đắk Lắk"),
        "471" => array("maqh"=>"648","name"=>"Huyện Cư M'gar","matp"=>"Đắk Lắk"),
        "472" => array("maqh"=>"649","name"=>"Huyện Krông Búk","matp"=>"Đắk Lắk"),
        "473" => array("maqh"=>"650","name"=>"Huyện Krông Năng","matp"=>"Đắk Lắk"),
        "474" => array("maqh"=>"651","name"=>"Huyện Ea Kar","matp"=>"Đắk Lắk"),
        "475" => array("maqh"=>"652","name"=>"Huyện M'Đrắk","matp"=>"Đắk Lắk"),
        "476" => array("maqh"=>"653","name"=>"Huyện Krông Bông","matp"=>"Đắk Lắk"),
        "477" => array("maqh"=>"654","name"=>"Huyện Krông Pắc","matp"=>"Đắk Lắk"),
        "478" => array("maqh"=>"655","name"=>"Huyện Krông A Na","matp"=>"Đắk Lắk"),
        "479" => array("maqh"=>"656","name"=>"Huyện Lắk","matp"=>"Đắk Lắk"),
        "480" => array("maqh"=>"657","name"=>"Huyện Cư Kuin","matp"=>"Đắk Lắk"),
        "481" => array("maqh"=>"660","name"=>"Thành phố Gia Nghĩa","matp"=>"Đắk Nông"),
        "482" => array("maqh"=>"661","name"=>"Huyện Đăk Glong","matp"=>"Đắk Nông"),
        "483" => array("maqh"=>"662","name"=>"Huyện Cư Jút","matp"=>"Đắk Nông"),
        "484" => array("maqh"=>"663","name"=>"Huyện Đắk Mil","matp"=>"Đắk Nông"),
        "485" => array("maqh"=>"664","name"=>"Huyện Krông Nô","matp"=>"Đắk Nông"),
        "486" => array("maqh"=>"665","name"=>"Huyện Đắk Song","matp"=>"Đắk Nông"),
        "487" => array("maqh"=>"666","name"=>"Huyện Đắk R'Lấp","matp"=>"Đắk Nông"),
        "488" => array("maqh"=>"667","name"=>"Huyện Tuy Đức","matp"=>"Đắk Nông"),
        "489" => array("maqh"=>"672","name"=>"Thành phố Đà Lạt","matp"=>"Lâm Đồng"),
        "490" => array("maqh"=>"673","name"=>"Thành phố Bảo Lộc","matp"=>"Lâm Đồng"),
        "491" => array("maqh"=>"674","name"=>"Huyện Đam Rông","matp"=>"Lâm Đồng"),
        "492" => array("maqh"=>"675","name"=>"Huyện Lạc Dương","matp"=>"Lâm Đồng"),
        "493" => array("maqh"=>"676","name"=>"Huyện Lâm Hà","matp"=>"Lâm Đồng"),
        "494" => array("maqh"=>"677","name"=>"Huyện Đơn Dương","matp"=>"Lâm Đồng"),
        "495" => array("maqh"=>"678","name"=>"Huyện Đức Trọng","matp"=>"Lâm Đồng"),
        "496" => array("maqh"=>"679","name"=>"Huyện Di Linh","matp"=>"Lâm Đồng"),
        "497" => array("maqh"=>"680","name"=>"Huyện Bảo Lâm","matp"=>"Lâm Đồng"),
        "498" => array("maqh"=>"681","name"=>"Huyện Đạ Huoai","matp"=>"Lâm Đồng"),
        "499" => array("maqh"=>"682","name"=>"Huyện Đạ Tẻh","matp"=>"Lâm Đồng"),
        "500" => array("maqh"=>"683","name"=>"Huyện Cát Tiên","matp"=>"Lâm Đồng"),
        "501" => array("maqh"=>"688","name"=>"Thị xã Phước Long","matp"=>"Bình Phước"),
        "502" => array("maqh"=>"689","name"=>"Thành phố Đồng Xoài","matp"=>"Bình Phước"),
        "503" => array("maqh"=>"690","name"=>"Thị xã Bình Long","matp"=>"Bình Phước"),
        "504" => array("maqh"=>"691","name"=>"Huyện Bù Gia Mập","matp"=>"Bình Phước"),
        "505" => array("maqh"=>"692","name"=>"Huyện Lộc Ninh","matp"=>"Bình Phước"),
        "506" => array("maqh"=>"693","name"=>"Huyện Bù Đốp","matp"=>"Bình Phước"),
        "507" => array("maqh"=>"694","name"=>"Huyện Hớn Quản","matp"=>"Bình Phước"),
        "508" => array("maqh"=>"695","name"=>"Huyện Đồng Phú","matp"=>"Bình Phước"),
        "509" => array("maqh"=>"696","name"=>"Huyện Bù Đăng","matp"=>"Bình Phước"),
        "510" => array("maqh"=>"697","name"=>"Huyện Chơn Thành","matp"=>"Bình Phước"),
        "511" => array("maqh"=>"698","name"=>"Huyện Phú Riềng","matp"=>"Bình Phước"),
        "512" => array("maqh"=>"703","name"=>"Thành phố Tây Ninh","matp"=>"Tây Ninh"),
        "513" => array("maqh"=>"705","name"=>"Huyện Tân Biên","matp"=>"Tây Ninh"),
        "514" => array("maqh"=>"706","name"=>"Huyện Tân Châu","matp"=>"Tây Ninh"),
        "515" => array("maqh"=>"707","name"=>"Huyện Dương Minh Châu","matp"=>"Tây Ninh"),
        "516" => array("maqh"=>"708","name"=>"Huyện Châu Thành","matp"=>"Tây Ninh"),
        "517" => array("maqh"=>"709","name"=>"Thị xã Hòa Thành","matp"=>"Tây Ninh"),
        "518" => array("maqh"=>"710","name"=>"Huyện Gò Dầu","matp"=>"Tây Ninh"),
        "519" => array("maqh"=>"711","name"=>"Huyện Bến Cầu","matp"=>"Tây Ninh"),
        "520" => array("maqh"=>"712","name"=>"Thị xã Trảng Bàng","matp"=>"Tây Ninh"),
        "521" => array("maqh"=>"718","name"=>"Thành phố Thủ Dầu Một","matp"=>"Bình Dương"),
        "522" => array("maqh"=>"719","name"=>"Huyện Bàu Bàng","matp"=>"Bình Dương"),
        "523" => array("maqh"=>"720","name"=>"Huyện Dầu Tiếng","matp"=>"Bình Dương"),
        "524" => array("maqh"=>"721","name"=>"Thị xã Bến Cát","matp"=>"Bình Dương"),
        "525" => array("maqh"=>"722","name"=>"Huyện Phú Giáo","matp"=>"Bình Dương"),
        "526" => array("maqh"=>"723","name"=>"Thị xã Tân Uyên","matp"=>"Bình Dương"),
        "527" => array("maqh"=>"724","name"=>"Thành phố Dĩ An","matp"=>"Bình Dương"),
        "528" => array("maqh"=>"725","name"=>"Thành phố Thuận An","matp"=>"Bình Dương"),
        "529" => array("maqh"=>"726","name"=>"Huyện Bắc Tân Uyên","matp"=>"Bình Dương"),
        "530" => array("maqh"=>"731","name"=>"Thành phố Biên Hòa","matp"=>"Đồng Nai"),
        "531" => array("maqh"=>"732","name"=>"Thành phố Long Khánh","matp"=>"Đồng Nai"),
        "532" => array("maqh"=>"734","name"=>"Huyện Tân Phú","matp"=>"Đồng Nai"),
        "533" => array("maqh"=>"735","name"=>"Huyện Vĩnh Cửu","matp"=>"Đồng Nai"),
        "534" => array("maqh"=>"736","name"=>"Huyện Định Quán","matp"=>"Đồng Nai"),
        "535" => array("maqh"=>"737","name"=>"Huyện Trảng Bom","matp"=>"Đồng Nai"),
        "536" => array("maqh"=>"738","name"=>"Huyện Thống Nhất","matp"=>"Đồng Nai"),
        "537" => array("maqh"=>"739","name"=>"Huyện Cẩm Mỹ","matp"=>"Đồng Nai"),
        "538" => array("maqh"=>"740","name"=>"Huyện Long Thành","matp"=>"Đồng Nai"),
        "539" => array("maqh"=>"741","name"=>"Huyện Xuân Lộc","matp"=>"Đồng Nai"),
        "540" => array("maqh"=>"742","name"=>"Huyện Nhơn Trạch","matp"=>"Đồng Nai"),
        "541" => array("maqh"=>"747","name"=>"Thành phố Vũng Tàu","matp"=>"Bà Rịa - Vũng Tàu"),
        "542" => array("maqh"=>"748","name"=>"Thành phố Bà Rịa","matp"=>"Bà Rịa - Vũng Tàu"),
        "543" => array("maqh"=>"750","name"=>"Huyện Châu Đức","matp"=>"Bà Rịa - Vũng Tàu"),
        "544" => array("maqh"=>"751","name"=>"Huyện Xuyên Mộc","matp"=>"Bà Rịa - Vũng Tàu"),
        "545" => array("maqh"=>"752","name"=>"Huyện Long Điền","matp"=>"Bà Rịa - Vũng Tàu"),
        "546" => array("maqh"=>"753","name"=>"Huyện Đất Đỏ","matp"=>"Bà Rịa - Vũng Tàu"),
        "547" => array("maqh"=>"754","name"=>"Thị xã Phú Mỹ","matp"=>"Bà Rịa - Vũng Tàu"),
        "548" => array("maqh"=>"755","name"=>"Huyện Côn Đảo","matp"=>"Bà Rịa - Vũng Tàu"),
        "549" => array("maqh"=>"760","name"=>"Quận 1","matp"=>"TP Hồ Chí Minh"),
        "550" => array("maqh"=>"761","name"=>"Quận 12","matp"=>"TP Hồ Chí Minh"),
        "551" => array("maqh"=>"764","name"=>"Quận Gò Vấp","matp"=>"TP Hồ Chí Minh"),
        "552" => array("maqh"=>"765","name"=>"Quận Bình Thạnh","matp"=>"TP Hồ Chí Minh"),
        "553" => array("maqh"=>"766","name"=>"Quận Tân Bình","matp"=>"TP Hồ Chí Minh"),
        "554" => array("maqh"=>"767","name"=>"Quận Tân Phú","matp"=>"TP Hồ Chí Minh"),
        "555" => array("maqh"=>"768","name"=>"Quận Phú Nhuận","matp"=>"TP Hồ Chí Minh"),
        "556" => array("maqh"=>"769","name"=>"Thành phố Thủ Đức","matp"=>"TP Hồ Chí Minh"),
        "557" => array("maqh"=>"770","name"=>"Quận 3","matp"=>"TP Hồ Chí Minh"),
        "558" => array("maqh"=>"771","name"=>"Quận 10","matp"=>"TP Hồ Chí Minh"),
        "559" => array("maqh"=>"772","name"=>"Quận 11","matp"=>"TP Hồ Chí Minh"),
        "560" => array("maqh"=>"773","name"=>"Quận 4","matp"=>"TP Hồ Chí Minh"),
        "561" => array("maqh"=>"774","name"=>"Quận 5","matp"=>"TP Hồ Chí Minh"),
        "562" => array("maqh"=>"775","name"=>"Quận 6","matp"=>"TP Hồ Chí Minh"),
        "563" => array("maqh"=>"776","name"=>"Quận 8","matp"=>"TP Hồ Chí Minh"),
        "564" => array("maqh"=>"777","name"=>"Quận Bình Tân","matp"=>"TP Hồ Chí Minh"),
        "565" => array("maqh"=>"778","name"=>"Quận 7","matp"=>"TP Hồ Chí Minh"),
        "566" => array("maqh"=>"783","name"=>"Huyện Củ Chi","matp"=>"TP Hồ Chí Minh"),
        "567" => array("maqh"=>"784","name"=>"Huyện Hóc Môn","matp"=>"TP Hồ Chí Minh"),
        "568" => array("maqh"=>"785","name"=>"Huyện Bình Chánh","matp"=>"TP Hồ Chí Minh"),
        "569" => array("maqh"=>"786","name"=>"Huyện Nhà Bè","matp"=>"TP Hồ Chí Minh"),
        "570" => array("maqh"=>"787","name"=>"Huyện Cần Giờ","matp"=>"TP Hồ Chí Minh"),
        "571" => array("maqh"=>"794","name"=>"Thành phố Tân An","matp"=>"Long An"),
        "572" => array("maqh"=>"795","name"=>"Thị xã Kiến Tường","matp"=>"Long An"),
        "573" => array("maqh"=>"796","name"=>"Huyện Tân Hưng","matp"=>"Long An"),
        "574" => array("maqh"=>"797","name"=>"Huyện Vĩnh Hưng","matp"=>"Long An"),
        "575" => array("maqh"=>"798","name"=>"Huyện Mộc Hóa","matp"=>"Long An"),
        "576" => array("maqh"=>"799","name"=>"Huyện Tân Thạnh","matp"=>"Long An"),
        "577" => array("maqh"=>"800","name"=>"Huyện Thạnh Hóa","matp"=>"Long An"),
        "578" => array("maqh"=>"801","name"=>"Huyện Đức Huệ","matp"=>"Long An"),
        "579" => array("maqh"=>"802","name"=>"Huyện Đức Hòa","matp"=>"Long An"),
        "580" => array("maqh"=>"803","name"=>"Huyện Bến Lức","matp"=>"Long An"),
        "581" => array("maqh"=>"804","name"=>"Huyện Thủ Thừa","matp"=>"Long An"),
        "582" => array("maqh"=>"805","name"=>"Huyện Tân Trụ","matp"=>"Long An"),
        "583" => array("maqh"=>"806","name"=>"Huyện Cần Đước","matp"=>"Long An"),
        "584" => array("maqh"=>"807","name"=>"Huyện Cần Giuộc","matp"=>"Long An"),
        "585" => array("maqh"=>"808","name"=>"Huyện Châu Thành","matp"=>"Long An"),
        "586" => array("maqh"=>"815","name"=>"Thành phố Mỹ Tho","matp"=>"Tiền Giang"),
        "587" => array("maqh"=>"816","name"=>"Thị xã Gò Công","matp"=>"Tiền Giang"),
        "588" => array("maqh"=>"817","name"=>"Thị xã Cai Lậy","matp"=>"Tiền Giang"),
        "589" => array("maqh"=>"818","name"=>"Huyện Tân Phước","matp"=>"Tiền Giang"),
        "590" => array("maqh"=>"819","name"=>"Huyện Cái Bè","matp"=>"Tiền Giang"),
        "591" => array("maqh"=>"820","name"=>"Huyện Cai Lậy","matp"=>"Tiền Giang"),
        "592" => array("maqh"=>"821","name"=>"Huyện Châu Thành","matp"=>"Tiền Giang"),
        "593" => array("maqh"=>"822","name"=>"Huyện Chợ Gạo","matp"=>"Tiền Giang"),
        "594" => array("maqh"=>"823","name"=>"Huyện Gò Công Tây","matp"=>"Tiền Giang"),
        "595" => array("maqh"=>"824","name"=>"Huyện Gò Công Đông","matp"=>"Tiền Giang"),
        "596" => array("maqh"=>"825","name"=>"Huyện Tân Phú Đông","matp"=>"Tiền Giang"),
        "597" => array("maqh"=>"829","name"=>"Thành phố Bến Tre","matp"=>"Bến Tre"),
        "598" => array("maqh"=>"831","name"=>"Huyện Châu Thành","matp"=>"Bến Tre"),
        "599" => array("maqh"=>"832","name"=>"Huyện Chợ Lách","matp"=>"Bến Tre"),
        "600" => array("maqh"=>"833","name"=>"Huyện Mỏ Cày Nam","matp"=>"Bến Tre"),
        "601" => array("maqh"=>"834","name"=>"Huyện Giồng Trôm","matp"=>"Bến Tre"),
        "602" => array("maqh"=>"835","name"=>"Huyện Bình Đại","matp"=>"Bến Tre"),
        "603" => array("maqh"=>"836","name"=>"Huyện Ba Tri","matp"=>"Bến Tre"),
        "604" => array("maqh"=>"837","name"=>"Huyện Thạnh Phú","matp"=>"Bến Tre"),
        "605" => array("maqh"=>"838","name"=>"Huyện Mỏ Cày Bắc","matp"=>"Bến Tre"),
        "606" => array("maqh"=>"842","name"=>"Thành phố Trà Vinh","matp"=>"Trà Vinh"),
        "607" => array("maqh"=>"844","name"=>"Huyện Càng Long","matp"=>"Trà Vinh"),
        "608" => array("maqh"=>"845","name"=>"Huyện Cầu Kè","matp"=>"Trà Vinh"),
        "609" => array("maqh"=>"846","name"=>"Huyện Tiểu Cần","matp"=>"Trà Vinh"),
        "610" => array("maqh"=>"847","name"=>"Huyện Châu Thành","matp"=>"Trà Vinh"),
        "611" => array("maqh"=>"848","name"=>"Huyện Cầu Ngang","matp"=>"Trà Vinh"),
        "612" => array("maqh"=>"849","name"=>"Huyện Trà Cú","matp"=>"Trà Vinh"),
        "613" => array("maqh"=>"850","name"=>"Huyện Duyên Hải","matp"=>"Trà Vinh"),
        "614" => array("maqh"=>"851","name"=>"Thị xã Duyên Hải","matp"=>"Trà Vinh"),
        "615" => array("maqh"=>"855","name"=>"Thành phố Vĩnh Long","matp"=>"Vĩnh Long"),
        "616" => array("maqh"=>"857","name"=>"Huyện Long Hồ","matp"=>"Vĩnh Long"),
        "617" => array("maqh"=>"858","name"=>"Huyện Mang Thít","matp"=>"Vĩnh Long"),
        "618" => array("maqh"=>"859","name"=>"Huyện Vũng Liêm","matp"=>"Vĩnh Long"),
        "619" => array("maqh"=>"860","name"=>"Huyện Tam Bình","matp"=>"Vĩnh Long"),
        "620" => array("maqh"=>"861","name"=>"Thị xã Bình Minh","matp"=>"Vĩnh Long"),
        "621" => array("maqh"=>"862","name"=>"Huyện Trà Ôn","matp"=>"Vĩnh Long"),
        "622" => array("maqh"=>"863","name"=>"Huyện Bình Tân","matp"=>"Vĩnh Long"),
        "623" => array("maqh"=>"866","name"=>"Thành phố Cao Lãnh","matp"=>"Đồng Tháp"),
        "624" => array("maqh"=>"867","name"=>"Thành phố Sa Đéc","matp"=>"Đồng Tháp"),
        "625" => array("maqh"=>"868","name"=>"Thành phố Hồng Ngự","matp"=>"Đồng Tháp"),
        "626" => array("maqh"=>"869","name"=>"Huyện Tân Hồng","matp"=>"Đồng Tháp"),
        "627" => array("maqh"=>"870","name"=>"Huyện Hồng Ngự","matp"=>"Đồng Tháp"),
        "628" => array("maqh"=>"871","name"=>"Huyện Tam Nông","matp"=>"Đồng Tháp"),
        "629" => array("maqh"=>"872","name"=>"Huyện Tháp Mười","matp"=>"Đồng Tháp"),
        "630" => array("maqh"=>"873","name"=>"Huyện Cao Lãnh","matp"=>"Đồng Tháp"),
        "631" => array("maqh"=>"874","name"=>"Huyện Thanh Bình","matp"=>"Đồng Tháp"),
        "632" => array("maqh"=>"875","name"=>"Huyện Lấp Vò","matp"=>"Đồng Tháp"),
        "633" => array("maqh"=>"876","name"=>"Huyện Lai Vung","matp"=>"Đồng Tháp"),
        "634" => array("maqh"=>"877","name"=>"Huyện Châu Thành","matp"=>"Đồng Tháp"),
        "635" => array("maqh"=>"883","name"=>"Thành phố Long Xuyên","matp"=>"An Giang"),
        "636" => array("maqh"=>"884","name"=>"Thành phố Châu Đốc","matp"=>"An Giang"),
        "637" => array("maqh"=>"886","name"=>"Huyện An Phú","matp"=>"An Giang"),
        "638" => array("maqh"=>"887","name"=>"Thị xã Tân Châu","matp"=>"An Giang"),
        "639" => array("maqh"=>"888","name"=>"Huyện Phú Tân","matp"=>"An Giang"),
        "640" => array("maqh"=>"889","name"=>"Huyện Châu Phú","matp"=>"An Giang"),
        "641" => array("maqh"=>"890","name"=>"Huyện Tịnh Biên","matp"=>"An Giang"),
        "642" => array("maqh"=>"891","name"=>"Huyện Tri Tôn","matp"=>"An Giang"),
        "643" => array("maqh"=>"892","name"=>"Huyện Châu Thành","matp"=>"An Giang"),
        "644" => array("maqh"=>"893","name"=>"Huyện Chợ Mới","matp"=>"An Giang"),
        "645" => array("maqh"=>"894","name"=>"Huyện Thoại Sơn","matp"=>"An Giang"),
        "646" => array("maqh"=>"899","name"=>"Thành phố Rạch Giá","matp"=>"Kiên Giang"),
        "647" => array("maqh"=>"900","name"=>"Thành phố Hà Tiên","matp"=>"Kiên Giang"),
        "648" => array("maqh"=>"902","name"=>"Huyện Kiên Lương","matp"=>"Kiên Giang"),
        "649" => array("maqh"=>"903","name"=>"Huyện Hòn Đất","matp"=>"Kiên Giang"),
        "650" => array("maqh"=>"904","name"=>"Huyện Tân Hiệp","matp"=>"Kiên Giang"),
        "651" => array("maqh"=>"905","name"=>"Huyện Châu Thành","matp"=>"Kiên Giang"),
        "652" => array("maqh"=>"906","name"=>"Huyện Giồng Riềng","matp"=>"Kiên Giang"),
        "653" => array("maqh"=>"907","name"=>"Huyện Gò Quao","matp"=>"Kiên Giang"),
        "654" => array("maqh"=>"908","name"=>"Huyện An Biên","matp"=>"Kiên Giang"),
        "655" => array("maqh"=>"909","name"=>"Huyện An Minh","matp"=>"Kiên Giang"),
        "656" => array("maqh"=>"910","name"=>"Huyện Vĩnh Thuận","matp"=>"Kiên Giang"),
        "657" => array("maqh"=>"911","name"=>"Thành phố Phú Quốc","matp"=>"Kiên Giang"),
        "658" => array("maqh"=>"912","name"=>"Huyện Kiên Hải","matp"=>"Kiên Giang"),
        "659" => array("maqh"=>"913","name"=>"Huyện U Minh Thượng","matp"=>"Kiên Giang"),
        "660" => array("maqh"=>"914","name"=>"Huyện Giang Thành","matp"=>"Kiên Giang"),
        "661" => array("maqh"=>"916","name"=>"Quận Ninh Kiều","matp"=>"Cần Thơ"),
        "662" => array("maqh"=>"917","name"=>"Quận Ô Môn","matp"=>"Cần Thơ"),
        "663" => array("maqh"=>"918","name"=>"Quận Bình Thuỷ","matp"=>"Cần Thơ"),
        "664" => array("maqh"=>"919","name"=>"Quận Cái Răng","matp"=>"Cần Thơ"),
        "665" => array("maqh"=>"923","name"=>"Quận Thốt Nốt","matp"=>"Cần Thơ"),
        "666" => array("maqh"=>"924","name"=>"Huyện Vĩnh Thạnh","matp"=>"Cần Thơ"),
        "667" => array("maqh"=>"925","name"=>"Huyện Cờ Đỏ","matp"=>"Cần Thơ"),
        "668" => array("maqh"=>"926","name"=>"Huyện Phong Điền","matp"=>"Cần Thơ"),
        "669" => array("maqh"=>"927","name"=>"Huyện Thới Lai","matp"=>"Cần Thơ"),
        "670" => array("maqh"=>"930","name"=>"Thành phố Vị Thanh","matp"=>"Hậu Giang"),
        "671" => array("maqh"=>"931","name"=>"Thành phố Ngã Bảy","matp"=>"Hậu Giang"),
        "672" => array("maqh"=>"932","name"=>"Huyện Châu Thành A","matp"=>"Hậu Giang"),
        "673" => array("maqh"=>"933","name"=>"Huyện Châu Thành","matp"=>"Hậu Giang"),
        "674" => array("maqh"=>"934","name"=>"Huyện Phụng Hiệp","matp"=>"Hậu Giang"),
        "675" => array("maqh"=>"935","name"=>"Huyện Vị Thuỷ","matp"=>"Hậu Giang"),
        "676" => array("maqh"=>"936","name"=>"Huyện Long Mỹ","matp"=>"Hậu Giang"),
        "677" => array("maqh"=>"937","name"=>"Thị xã Long Mỹ","matp"=>"Hậu Giang"),
        "678" => array("maqh"=>"941","name"=>"Thành phố Sóc Trăng","matp"=>"Sóc Trăng"),
        "679" => array("maqh"=>"942","name"=>"Huyện Châu Thành","matp"=>"Sóc Trăng"),
        "680" => array("maqh"=>"943","name"=>"Huyện Kế Sách","matp"=>"Sóc Trăng"),
        "681" => array("maqh"=>"944","name"=>"Huyện Mỹ Tú","matp"=>"Sóc Trăng"),
        "682" => array("maqh"=>"945","name"=>"Huyện Cù Lao Dung","matp"=>"Sóc Trăng"),
        "683" => array("maqh"=>"946","name"=>"Huyện Long Phú","matp"=>"Sóc Trăng"),
        "684" => array("maqh"=>"947","name"=>"Huyện Mỹ Xuyên","matp"=>"Sóc Trăng"),
        "685" => array("maqh"=>"948","name"=>"Thị xã Ngã Năm","matp"=>"Sóc Trăng"),
        "686" => array("maqh"=>"949","name"=>"Huyện Thạnh Trị","matp"=>"Sóc Trăng"),
        "687" => array("maqh"=>"950","name"=>"Thị xã Vĩnh Châu","matp"=>"Sóc Trăng"),
        "688" => array("maqh"=>"951","name"=>"Huyện Trần Đề","matp"=>"Sóc Trăng"),
        "689" => array("maqh"=>"954","name"=>"Thành phố Bạc Liêu","matp"=>"Bạc Liêu"),
        "690" => array("maqh"=>"956","name"=>"Huyện Hồng Dân","matp"=>"Bạc Liêu"),
        "691" => array("maqh"=>"957","name"=>"Huyện Phước Long","matp"=>"Bạc Liêu"),
        "692" => array("maqh"=>"958","name"=>"Huyện Vĩnh Lợi","matp"=>"Bạc Liêu"),
        "693" => array("maqh"=>"959","name"=>"Thị xã Giá Rai","matp"=>"Bạc Liêu"),
        "694" => array("maqh"=>"960","name"=>"Huyện Đông Hải","matp"=>"Bạc Liêu"),
        "695" => array("maqh"=>"961","name"=>"Huyện Hoà Bình","matp"=>"Bạc Liêu"),
        "696" => array("maqh"=>"964","name"=>"Thành phố Cà Mau","matp"=>"Cà Mau"),
        "697" => array("maqh"=>"966","name"=>"Huyện U Minh","matp"=>"Cà Mau"),
        "698" => array("maqh"=>"967","name"=>"Huyện Thới Bình","matp"=>"Cà Mau"),
        "699" => array("maqh"=>"968","name"=>"Huyện Trần Văn Thời","matp"=>"Cà Mau"),
        "700" => array("maqh"=>"969","name"=>"Huyện Cái Nước","matp"=>"Cà Mau"),
        "701" => array("maqh"=>"970","name"=>"Huyện Đầm Dơi","matp"=>"Cà Mau"),
        "702" => array("maqh"=>"971","name"=>"Huyện Năm Căn","matp"=>"Cà Mau"),
        "703" => array("maqh"=>"972","name"=>"Huyện Phú Tân","matp"=>"Cà Mau"),
        "704" => array("maqh"=>"973","name"=>"Huyện Ngọc Hiển","matp"=>"Cà Mau"),
    );
}